[package]
name = "osrs-markov-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
# Make the wasm smaller & faster
lto = true
opt-level = "s"
codegen-units = 1
